using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Assignment1.Migrations
{
    /// <inheritdoc />
    public partial class Sync_Model : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'tickets'
    ) THEN
        CREATE TABLE public.""Tickets"" (
            ""TicketId"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""EventId"" integer NOT NULL,
            ""SeatNumber"" text NOT NULL,
            ""Price"" numeric(10,2) NOT NULL
        );
    END IF;
END
$$;");
            
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'tickets'
          AND column_name = 'id'
    )
    AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'tickets'
          AND column_name = 'ticketid'
    ) THEN
        ALTER TABLE public.""Tickets"" RENAME COLUMN ""Id"" TO ""TicketId"";
    END IF;
END
$$;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'tickets'
          AND column_name = 'ticketid'
    ) THEN
        ALTER TABLE public.""Tickets"" RENAME COLUMN ""TicketId"" TO ""Id"";
    END IF;
END
$$;");
        }
    }
}
