using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Assignment1.Migrations
{
    public partial class Events_Create : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.""Events"" (
    ""EventId"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""Title"" character varying(200) NOT NULL,
    ""Date"" timestamp with time zone NOT NULL,
    ""Location"" character varying(500),
    ""Price"" numeric(10,2)
);");
            
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'events'
          AND column_name = 'price'
          AND (numeric_precision IS NULL OR numeric_scale IS NULL)
    ) THEN
        ALTER TABLE public.""Events""
        ALTER COLUMN ""Price"" TYPE numeric(10,2);
    END IF;
END
$$;");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS public.""Events"" CASCADE;");
        }
    }
}